import type { CommunityWorkspace } from "./types";

export const creatorCommunityDemo: CommunityWorkspace = {
  communityId: "community-midnight-radio",
  name: "Midnight Radio Club",
  slug: "midnight-radio-club",
  category: "Creator community",
  creatorName: "Nova Vale",
  coverTagline: "Late-night creator community for mixes, edits, and member-only sessions.",
  heroPitch:
    "A full-stack creator community with sign-up, member profiles, channels, DMs, moderation, and optional paid membership powered by Tencent RTC Chat SDK.",
  nextDrop: "Backstage listening room opens in 2 hours",
  activeMembers: 1842,
  onlineNow: 216,
  members: [
    {
      id: "member-alina",
      name: "Alina Wu",
      handle: "alina.cutups",
      role: "member",
      status: "trial",
      tier: "free",
      bio: "Video editor joining for critique threads and live remix drops.",
      unreadCount: 4,
    },
    {
      id: "creator-nova",
      name: "Nova Vale",
      handle: "nova.vale",
      role: "creator",
      status: "active",
      tier: "inner-circle",
      bio: "Creator host running weekly drops, prompts, and premium backstage rooms.",
      unreadCount: 0,
    },
    {
      id: "moderator-iris",
      name: "Iris Cole",
      handle: "iris.mod",
      role: "moderator",
      status: "active",
      tier: "backstage",
      bio: "Moderator reviewing reports, invites, and tier access questions.",
      unreadCount: 1,
    },
  ],
  membershipTiers: [
    {
      id: "free",
      name: "Open Lobby",
      priceLabel: "$0",
      description: "Public channels, announcements, and community onboarding.",
      perks: ["Public chat", "Announcements", "Member directory"],
    },
    {
      id: "backstage",
      name: "Backstage",
      priceLabel: "$12/mo",
      description: "Private rooms, early drops, and creator direct-message office hours.",
      perks: ["Premium rooms", "Early releases", "Monthly DM office hours"],
    },
    {
      id: "inner-circle",
      name: "Inner Circle",
      priceLabel: "$39/mo",
      description: "Small-group feedback sessions and private archive access.",
      perks: ["Small-group sessions", "Archive access", "Priority creator replies"],
    },
  ],
  channels: [
    {
      id: "channel-announcements",
      name: "announcements",
      kind: "announcement",
      access: "free",
      topic: "Launches, schedule updates, and weekly prompts from the creator team.",
      unreadCount: 2,
      messages: [
        {
          id: "ann-1",
          author: "creator",
          name: "Nova Vale",
          time: "09:10",
          body: "Tonight's listening room opens at 9 PM. Backstage members get the stems 30 minutes early.",
        },
        {
          id: "ann-2",
          author: "system",
          name: "Tencent RTC Chat SDK",
          time: "09:11",
          body: "Announcement thread synced for community-midnight-radio. Members can revisit on any device.",
        },
      ],
    },
    {
      id: "channel-lounge",
      name: "creator-lounge",
      kind: "chat",
      access: "free",
      topic: "Daily member chat, intros, feedback requests, and creator prompts.",
      unreadCount: 6,
      messages: [
        {
          id: "lounge-1",
          author: "member",
          name: "Alina Wu",
          time: "09:18",
          body: "I just joined. Is there a thread for short-form editing feedback?",
        },
        {
          id: "lounge-2",
          author: "moderator",
          name: "Iris Cole",
          time: "09:20",
          body: "Yes. Drop it here today, then we will pin the critique room map before the live session.",
        },
      ],
    },
    {
      id: "channel-backstage",
      name: "backstage-room",
      kind: "premium",
      access: "backstage",
      topic: "Premium members-only room for early drops and creator Q&A.",
      unreadCount: 0,
      messages: [
        {
          id: "premium-1",
          author: "creator",
          name: "Nova Vale",
          time: "08:55",
          body: "Backstage members get first access to the alternate mix and a private debrief thread tonight.",
        },
      ],
    },
  ],
  directThreads: [
    {
      id: "dm-creator-alina",
      title: "Nova Vale · Member Office Hours",
      participants: ["creator-nova", "member-alina"],
      unreadCount: 1,
      messages: [
        {
          id: "dm-1",
          author: "member",
          name: "Alina Wu",
          time: "09:04",
          body: "I upgraded for office hours. Can I get feedback on my teaser cut before Friday?",
        },
        {
          id: "dm-2",
          author: "creator",
          name: "Nova Vale",
          time: "09:07",
          body: "Yes. Send the draft here and I will leave notes in this thread before the stream.",
        },
      ],
    },
  ],
  reports: [
    {
      id: "report-101",
      reason: "Spoiler clip posted in the public lounge before release.",
      status: "reviewing",
      reporter: "Kai",
      target: "member-48",
    },
    {
      id: "report-102",
      reason: "Join request asks for access to premium room without subscription.",
      status: "open",
      reporter: "Billing bot",
      target: "member-77",
    },
  ],
};
