import type { EcommerceWorkspace } from "./types";

export const ecommerceOrderChatDemo: EcommerceWorkspace = {
  storeId: "store-harbor-thread",
  storeName: "Harbor Thread Market",
  category: "Ecommerce buyer-seller threads",
  sellerName: "Mira Santos",
  coverTagline: "Boutique home-goods storefront with product questions and order threads before and after purchase.",
  heroPitch:
    "A full-stack ecommerce app with buyer sign-up, product catalog, product chat, Stripe-ready checkout, and post-purchase order threads powered by Tencent RTC Chat SDK.",
  nextShipment: "3 paid orders scheduled for tonight's dispatch window",
  gmv: 18420,
  users: [
    {
      id: "buyer-lena",
      name: "Lena Park",
      handle: "lena.orders",
      role: "buyer",
      status: "signed-up",
      bio: "First-time buyer asking about finish options and delivery timing.",
      unreadCount: 3,
    },
    {
      id: "seller-mira",
      name: "Mira Santos",
      handle: "mira.store",
      role: "seller",
      status: "verified",
      bio: "Independent seller managing listings, order replies, and post-purchase follow-up.",
      unreadCount: 0,
    },
    {
      id: "ops-joel",
      name: "Joel Chen",
      handle: "ops.harbor",
      role: "ops",
      status: "verified",
      bio: "Store operator watching payment exceptions and shipment handoff.",
      unreadCount: 1,
    },
  ],
  products: [
    {
      id: "product-lamp",
      title: "Reed Table Lamp",
      category: "Lighting",
      price: 129,
      inventory: 7,
      sellerId: "seller-mira",
      summary: "Hand-finished table lamp with warm brass hardware and linen shade.",
      unreadCount: 4,
    },
    {
      id: "product-throw",
      title: "Harbor Wool Throw",
      category: "Textiles",
      price: 86,
      inventory: 11,
      sellerId: "seller-mira",
      summary: "Soft wool throw with custom color options and gift-note support.",
      unreadCount: 1,
    },
    {
      id: "product-shelf",
      title: "Oak Entry Shelf",
      category: "Furniture",
      price: 219,
      inventory: 3,
      sellerId: "seller-mira",
      summary: "Compact handmade shelf with wall-mount kit and assembly notes.",
      unreadCount: 0,
    },
  ],
  cart: [
    {
      id: "cart-1",
      productId: "product-lamp",
      title: "Reed Table Lamp",
      quantity: 1,
      unitPrice: 129,
    },
    {
      id: "cart-2",
      productId: "product-throw",
      title: "Harbor Wool Throw",
      quantity: 1,
      unitPrice: 86,
    },
  ],
  threads: [
    {
      id: "thread-lamp-pre-sale",
      title: "Reed Table Lamp · Buyer questions",
      productId: "product-lamp",
      stage: "pre-sale",
      unreadCount: 4,
      messages: [
        {
          id: "t1",
          author: "buyer",
          name: "Lena Park",
          time: "09:12",
          body: "Can this lamp ship before Friday, and do you have a darker linen shade?",
        },
        {
          id: "t2",
          author: "seller",
          name: "Mira Santos",
          time: "09:15",
          body: "Yes. I can ship tomorrow morning, and I have an oat and charcoal shade ready for this batch.",
        },
        {
          id: "t3",
          author: "system",
          name: "Tencent RTC Chat SDK",
          time: "09:16",
          body: "Buyer-seller thread mapped to product-lamp. History can continue into the order thread after payment.",
        },
      ],
    },
    {
      id: "thread-order-3021",
      title: "Order #3021 · Reed Table Lamp",
      productId: "product-lamp",
      orderId: "order-3021",
      stage: "paid",
      unreadCount: 2,
      messages: [
        {
          id: "o1",
          author: "seller",
          name: "Mira Santos",
          time: "08:52",
          body: "Payment cleared. I am packing the lamp now and will send tracking in this same thread.",
        },
        {
          id: "o2",
          author: "buyer",
          name: "Lena Park",
          time: "08:56",
          body: "Perfect. Please include the gift note if possible.",
        },
      ],
    },
  ],
  orders: [
    {
      id: "order-3021",
      productId: "product-lamp",
      buyerId: "buyer-lena",
      sellerId: "seller-mira",
      stage: "paid",
      paymentProvider: "stripe",
      paymentStatus: "paid",
      amount: 129,
      note: "Gift note requested. Tracking not sent yet.",
    },
    {
      id: "order-3028",
      productId: "product-throw",
      buyerId: "buyer-lena",
      sellerId: "seller-mira",
      stage: "payment-pending",
      paymentProvider: "mock",
      paymentStatus: "pending",
      amount: 86,
      note: "Waiting for payment confirmation in the active order thread.",
    },
  ],
  sellerChecklist: [
    "Review buyer questions before purchase",
    "Confirm payment path: mock or Stripe",
    "Keep shipping and support updates in the same order thread",
    "Watch inventory and payment exceptions from the ops dashboard",
  ],
};
